openapi: 3.0.1
info:
  description: "API gateway for Customer App"
  version: "2021-04-14T17:00:39Z"
  title: "auth-service-gateway"
paths:
  /v1/dreamers:
    post:
      operationId: apileadspost
      responses: { }
      x-amazon-apigateway-integration:
        connectionId: "${vpc-id}"
        connectionType: "VPC_LINK"
        httpMethod: "POST"
        uri: "http://${url}/main/dreamers"
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
        type: "http_proxy"
  /v1/dreamers/{id}/kyc:
    post:
      operationId: apileadskycpost
      responses: { }
      parameters:
        - name: "id"
          in: "path"
          required: true
      x-amazon-apigateway-integration:
        connectionId: "${vpc-id}"
        connectionType: "VPC_LINK"
        httpMethod: "POST"
        uri: "http://${url}/main/dreamers/{id}/kyc"
        requestParameters:
          integration.request.path.id: "method.request.path.id"
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
        type: "http_proxy"
  /v1/dreamers/{id}/additional_details:
    post:
      operationId: apileadsadditionaldetailspost
      responses: { }
      parameters:
        - name: "id"
          in: "path"
          required: true
      x-amazon-apigateway-integration:
        connectionId: "${vpc-id}"
        connectionType: "VPC_LINK"
        httpMethod: "POST"
        uri: "http://${url}/main/dreamers/{id}/additional_details"
        requestParameters:
          integration.request.path.id: "method.request.path.id"
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
        type: "http_proxy"
  /v1/dreamers/{id}/payment_details:
    post:
      operationId: apileadspaymentdetailspost
      responses: { }
      parameters:
        - name: "id"
          in: "path"
          required: true
      x-amazon-apigateway-integration:
        connectionId: "${vpc-id}"
        connectionType: "VPC_LINK"
        httpMethod: "POST"
        uri: "http://${url}/main/dreamers/{id}/payment_details"
        requestParameters:
          integration.request.path.id: "method.request.path.id"
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
        type: "http_proxy"
  /v1/dreamers/{id}:
    get:
      operationId: apileadsgetbyid
      responses: { }
      parameters:
        - name: "id"
          in: "path"
          required: true
      x-amazon-apigateway-integration:
        connectionId: "${vpc-id}"
        connectionType: "VPC_LINK"
        httpMethod: "GET"
        uri: "http://${url}/main/dreamers/{id}"
        requestParameters:
          integration.request.path.id: "method.request.path.id"
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
        type: "http_proxy"
  /v1/shufti/callback:
    post:
      operationId: apishufticallbackpost
      responses: { }
      x-amazon-apigateway-integration:
        connectionId: "${vpc-id}"
        connectionType: "VPC_LINK"
        httpMethod: "POST"
        uri: "http://${url}/main/shufti/callback"
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
        type: "http_proxy"
  /v1/sendpulse/sendApprovalMessage:
    post:
      operationId: apisenpulseapprovalpost
      responses: { }
      x-amazon-apigateway-integration:
        connectionId: "${vpc-id}"
        connectionType: "VPC_LINK"
        httpMethod: "POST"
        uri: "http://${url}/main/sendpulse/sendApprovalMessage"
        passthroughBehavior: "when_no_match"
        timeoutInMillis: 29000
        type: "http_proxy"
components:
  schemas:
    Empty:
      title: "Empty Schema"
      type: "object"
